01:
	mvn compile exec:java -Dexec.mainClass="fr.julienlavocat.aoc.d01.Main01" 
02:
	mvn compile exec:java -Dexec.mainClass="fr.julienlavocat.aoc.d02.Main02" 
03:
	mvn compile exec:java -Dexec.mainClass="fr.julienlavocat.aoc.d03.Main03" 
